### ISSUE TITLE
tacolim_logo

### ISSUE THREAD

**Issue by tacolim** [jemagee/code_connection#2]
![tacolim_logo](https://cloud.githubusercontent.com/assets/25189972/23142797/c240f1d6-f78b-11e6-8a86-24c99b6b2e3a.png)

**Comment by jemagee** [comment]
Love to hear what people think of this, definitely like the vibe, and my wife loves it too :) What's everyone else think.

**Comment by tacolim** [comment]
Very quick avatar mock-ups to go with the logo idea.

![tacolim_avatar1](https://cloud.githubusercontent.com/assets/25189972/23261351/d2e7a29a-f9a3-11e6-9244-cffa74cd8f60.png)
![tacolim_avatar2](https://cloud.githubusercontent.com/assets/25189972/23261355/d6df6130-f9a3-11e6-9830-0b10a53871f1.png)

**Comment by krames12** [comment]
The design on both the logo and avatar is awesome! I like how simple it is overall.

**Comment by nayonnapurnell** [comment]
Simple yet relevant.  I love it.

**Comment by jemagee** [comment]
The opinions here and other places have been unanimous - so i'm going to close this issue and we will use this logo and avatars going forward - which will happen as well - i promise
